%% ########################################################
%% ======================================================
\begin{center}

%{\sf{\huge \sphinxDocumentTitle}} \\[5mm]
\begin{tabularx}{\textwidth}{ |L|L|L|L|L|L| }
        \hline
        \bf{Wydział:} \sphinxDocumentFaculty &
        \multicolumn{2}{|c|}{\bf{Autor/Autorzy:} \sphinxDocumentAuthor}
	\vline &
        \bf{Rok:} \sphinxDocumentYear &
        \bf{Grupa} \sphinxDocumentGroupID &
        \bf{Zespół} \sphinxDocumentTeam \\
        \hline

	\multicolumn{2}{|c|}{\bf{PRACOWNIA FIZYCZNA WFiS AGH}}
	\vline &
	\multicolumn{2}{c}{\sphinxDocumentTitle}  
	\vline &
        \multicolumn{2}{|c|}{\bf{Ćwiczenie nr:} \sphinxDocumentNumber}
	\vline \\[1cm]
      \hline

      \bf{Data wykonania} \sphinxDocumentTaskDate &
      \bf{Data oddania} \sphinxDocumentCreationDate &
      \bf{Zwrot do popr.} &
      \bf{Data oddania} \sphinxDocumentCorrectionDate&
      \bf{Data zaliczenia} &
	\bf{Ocena} \\[1cm]
      \hline

\end{tabularx}
\end{center}

%%\begin{center}
%%{\sf \sphinxDocumentTownAndYear}
%%\end{center}

%% ########################################################
%% ########################################################
%%\end{document}

