%% ########################################################
%% ======================================================
\begin{center}

%{\sf{\huge \sphinxDocumentTitle}} \\[5mm]
\begin{tabularx}{\textwidth}{ |L|L|L|L|L| }
        \hline
        Wydział \bf{\sphinxDocumentFaculty} &
        \sphinxDocumentAuthor &
        Rok \bf{\sphinxDocumentYear} &
        Grupa \bf{\sphinxDocumentGroupID} &
        Zespół \bf{\sphinxDocumentTeam} \\
        \hline

      \bf{PRACOWNIA FIZYCZNA WFiS AGH} &
      \multicolumn{3}{l}{\sphinxDocumentTitle}  
      \vline &
      Ćwiczenie nr: \bf{\sphinxDocumentNumber} \\
      \hline

      \bf{Data wykonania} \sphinxDocumentCreationDate &
      \bf{Data oddania} &
      \bf{Zwrot do popr.} &
      \bf{Data zaliczenia} &
      \bf{Ocena} \\
      \hline

%        Autor/Autorzy: \bf{\sphinxDocumentAuthor} &
%        Zespół nr: \bf{\sphinxDocumentTeam} \\
%        \hline
%        Ćwiczenie nr: \bf{\sphinxDocumentNumber} &
%        Wersja: \bf{\sphinxDocumentVersion} \\
%        \hline
\end{tabularx}
\end{center}

%%\begin{center}
%%{\sf \sphinxDocumentTownAndYear}
%%\end{center}

%% ########################################################
%% ########################################################
%%\end{document}

