%% ########################################################
%% ======================================================
\begin{center}

%{\sf{\huge \sphinxDocumentTitle}} \\[5mm]
\begin{tabularx}{\textwidth}{ |L|L|L|L|L|L| }
        \hline
	\sphinxDocumentFaculty &
	\multicolumn{2}{|c|}{\sphinxDocumentAuthor}
	\vline &
        Rok \bf{\sphinxDocumentYear} &
        Grupa \bf{\sphinxDocumentGroupID} &
        Zespół \bf{\sphinxDocumentTeam} \\
        \hline

	\multicolumn{2}{|c|}{\bf{PRACOWNIA FIZYCZNA WFiS AGH}}
	\vline &
	\multicolumn{2}{c}{\sphinxDocumentTitle}  
	\vline &
	\multicolumn{2}{|c|}{Ćwiczenie nr: \sphinxDocumentNumber}
	\vline \\[1cm]
      \hline

      \bf{Data wykonania} \sphinxDocumentTaskDate &
      \bf{Data oddania} \sphinxDocumentCreationDate &
      \bf{Zwrot do popr.} &
      \bf{Data oddania} \sphinxDocumentCorrectionDate&
      \bf{Data zaliczenia} &
	\bf{Ocena} \\[1cm]
      \hline

%        Autor/Autorzy: \bf{\sphinxDocumentAuthor} &
%        Zespół nr: \bf{\sphinxDocumentTeam} \\
%        \hline
%        Ćwiczenie nr: \bf{\sphinxDocumentNumber} &
%        Wersja: \bf{\sphinxDocumentVersion} \\
%        \hline
\end{tabularx}
\end{center}

%%\begin{center}
%%{\sf \sphinxDocumentTownAndYear}
%%\end{center}

%% ########################################################
%% ########################################################
%%\end{document}

